import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const production = process.argv[2] === "production";

// Externalize Node's built-in modules in both bare ("fs") and prefixed
// ("node:fs") forms; Obsidian's desktop runtime provides them.
const nodeBuiltins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeBuiltins,
	],
	// Embed sql.js's WebAssembly binary directly in main.js as a Uint8Array, so
	// the release ships the three files Obsidian recognizes (no side-car .wasm).
	loader: { ".wasm": "binary" },
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: production,
});

if (production) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
