import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const production = process.argv[2] === "production";

/**
 * sql.js ships its WebAssembly binary separately. The plugin loads it at
 * runtime from its own folder, so copy it next to main.js on every build.
 */
const copyWasm = {
	name: "copy-sql-wasm",
	setup(build) {
		build.onEnd(() => {
			const src = path.resolve("node_modules/sql.js/dist/sql-wasm.wasm");
			const dest = path.resolve("sql-wasm.wasm");
			if (fs.existsSync(src)) {
				fs.copyFileSync(src, dest);
			} else {
				console.warn("sql-wasm.wasm not found in node_modules; run npm install first.");
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: production,
	plugins: [copyWasm],
});

if (production) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
